label = "English"
locale = "en-us"
contentDir = "content/en"
weight = 1

[params]
  displayName = "EN"
  description = "Language Machines Network — a research network for socially situating language in AI systems"

[params.author]
  name = "Language Machines Network"
